[tools]
python = "3.14.5"
uv = "latest"

[env]
_.python.venv = { path = "florida-api/.venv", create = true }

[tasks.api-setup]
description = "Prepara o ambiente da API"
dir = "florida-api"
run = "uv sync"

[tasks.api-dev]
description = "Roda a API em modo de desenvolvimento"
dir = "florida-api"
run = "uv run fastapi dev main.py"
